# Generated by Django 5.0.7 on 2025-05-17 22:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dean', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
                ('birth_place', models.CharField(max_length=100)),
                ('governorate', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('directorate', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FatherInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('father_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('father_job', models.CharField(blank=True, max_length=100, null=True)),
                ('father_job_type', models.CharField(blank=True, max_length=100, null=True)),
                ('father_work_place', models.CharField(blank=True, max_length=200, null=True)),
                ('father_address', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marital_status', models.CharField(choices=[('single', 'أعزب'), ('married', 'متزوج'), ('divorced', 'مطلق'), ('widowed', 'أرمل')], max_length=10)),
                ('current_address', models.CharField(blank=True, max_length=200, null=True)),
                ('permanent_address', models.CharField(max_length=200)),
                ('id_number', models.CharField(max_length=50)),
                ('id_type', models.CharField(choices=[('personal', 'بطاقة شخصية'), ('election', 'بطاقة انتخابية'), ('passport', 'جواز سفر')], max_length=10)),
                ('id_issue_date', models.DateField(blank=True, null=True)),
                ('id_issue_place', models.CharField(blank=True, max_length=100, null=True)),
                ('current_job', models.CharField(blank=True, max_length=100, null=True)),
                ('work_place', models.CharField(blank=True, max_length=100, null=True)),
                ('employment_date', models.DateField(blank=True, null=True)),
                ('secondary_phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_type', models.CharField(choices=[('diploma', 'دبلوم'), ('bachelor', 'بكلريوس'), ('master', 'ماجستير')], max_length=10)),
                ('university', models.CharField(max_length=200)),
                ('gpa', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(4.0)])),
                ('certificate_image', models.FileField(upload_to='qualifications/')),
                ('qualification_date', models.DateField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(max_length=200)),
                ('nickname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_image', models.FileField(upload_to='documents/')),
                ('high_school_certificate', models.FileField(upload_to='documents/')),
                ('grade_data', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('criminal_record', models.FileField(upload_to='documents/')),
                ('birth_certificate', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dean.academicyear')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dean.department')),
                ('birth_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.birthinfo')),
                ('father_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.fatherinfo')),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.personalinfo')),
                ('qualifications', models.ManyToManyField(to='students.qualification')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('documents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentdocuments')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_rejected', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.application')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dean.stage')),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
                'unique_together': {('application', 'stage')},
            },
        ),
    ]
