# Generated by Django 5.0.7 on 2025-05-18 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('submitted', 'تم التقديم'), ('under_review', 'قيد المراجعة'), ('documents_reviewed', 'تم مراجعة المستندات'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], default='draft', max_length=20),
        ),
    ]
