# Generated by Django 5.0.7 on 2025-05-19 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_application_last_updated_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('submitted', 'تم التقديم'), ('documents_reviewed', 'تم مراجعة المستندات'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], default='draft', max_length=20),
        ),
    ]
