# Generated by Django 5.0.7 on 2025-05-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationstatus',
            name='is_returned',
            field=models.BooleanField(default=False, verbose_name='معاد للمراجعة'),
        ),
    ]
