# Generated by Django 5.0.7 on 2025-05-26 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_applicationstatus_is_returned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationstatus',
            name='is_returned',
        ),
    ]
