# Generated by Django 5.0.7 on 2025-05-17 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('committee', '0001_initial'),
        ('dean', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeeopinion',
            name='application_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.applicationstatus'),
        ),
        migrations.AddField(
            model_name='committeeopinion',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dean.employee'),
        ),
        migrations.AddField(
            model_name='stageresult',
            name='application_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.applicationstatus'),
        ),
        migrations.AddField(
            model_name='stageresult',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dean.employee'),
        ),
        migrations.AlterUniqueTogether(
            name='committeeopinion',
            unique_together={('employee', 'application_status')},
        ),
    ]
