# Generated by Django 5.0.7 on 2025-05-27 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dean', '0002_initial'),
        ('students', '0005_remove_applicationstatus_is_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='الطالب المستهدف'),
        ),
    ]
